name = "cloudflare-do-study"
main = "src/index.ts"
compatibility_date = "2023-03-26"

[site]
bucket = "./dist"

[durable_objects]
bindings = [
  {name = "rooms", class_name = "ChatRoom"},
]

[[migrations]]
new_classes = [ "ChatRoom"]
tag = "v1"
